version: "3.7"
services:
    # api:
    #     image: jeffrygonzalez/bes100api:latest
    #     depends_on: 
    #         - sql
    #     ports:
    #         - 80:80
    #     environment: 
    #         - ConnectionStrings__library=server=sql;database=books_docker;user=sa;password=TokyoJoe138!
    sql:
        image: jeffrygonzalez/sql-bes200-june-2021:latest
        ports:
            - 1433:1433