# Generated by Django 3.2.4 on 2021-06-16 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_departments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentID',
            new_name='DepartmentID',
        ),
        migrations.RenameField(
            model_name='departments',
            old_name='DepartmentName',
            new_name='DeparttmentName',
        ),
    ]
