# Generated by Django 3.2.4 on 2021-06-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_auto_20210616_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departments',
            old_name='DeparttmentName',
            new_name='DepartmentName',
        ),
    ]
