# Generated by Django 3.2.4 on 2021-06-16 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_rename_departtmentname_departments_departmentname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmpoyeeId',
            new_name='DateOfJoining',
        ),
    ]
