# Generated by Django 3.2.4 on 2021-06-16 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0005_rename_empoyeeid_employees_dateofjoining'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='EmployeeId',
            new_name='EmployeeID',
        ),
    ]
